import type { CMSState } from "./types"

export const defaultState: CMSState = {
  locale: "ar",
  design: {
    theme: "system",
    palette: "violet-emerald",
    anim: {
      enableReveal: true,
      intensity: 1,
      parallax: 14,
    },
  },
  blocks: [
    { id: "hero", type: "hero", enabled: true },
    { id: "logos", type: "logos", enabled: true },
    { id: "features", type: "features", enabled: true },
    { id: "services", type: "services", enabled: true },
    { id: "payments", type: "payments", enabled: true },
    { id: "testimonials", type: "testimonials", enabled: true },
    { id: "cta", type: "cta", enabled: true },
    { id: "faq", type: "faq", enabled: true },
    { id: "contact", type: "contact", enabled: true },
  ],
  content: {
    ar: {
      site: {
        name: "kyctrust",
        description: "منصة حديثة لحلول الحسابات البنكية الإلكترونية والمدفوعات الرقمية الآمنة",
        phone: "+20-106-245-3344",
        tagline: "هويتك المالية الجديدة",
        logoSrc: "/generic-app-logo.png",
      },
      hero: {
        title: "kyctrust",
        subtitle: "منصة متكاملة للخدمات المالية الرقمية",
        description: "احصل على أفضل الحسابات البنكية والمحافظ الرقمية بأمان وسرعة",
        cta: "ابدأ رحلتك",
        secondary: "تصفح الخدمات",
        stats: [
          { number: "1000+", label: "عميل راضٍ" },
          { number: "24/7", label: "دعم فني" },
          { number: "99.9%", label: "معدل النجاح" },
          { number: "15+", label: "خدمة" },
        ],
      },
      logos: [
        { name: "Payoneer", src: "/images/logos/payoneer.png", url: "https://www.payoneer.com" },
        { name: "Wise", src: "/images/logos/wise.png", url: "https://wise.com" },
        { name: "Skrill", src: "/images/logos/skrill.png", url: "https://www.skrill.com" },
        { name: "Neteller", src: "/images/logos/neteller.png", url: "https://www.neteller.com" },
        { name: "PayPal", src: "/images/logos/paypal.png", url: "https://www.paypal.com" },
        { name: "OKX", src: "/images/logos/okx.png", url: "https://www.okx.com" },
        { name: "Bybit", src: "/images/logos/bybit.png", url: "https://www.bybit.com" },
        { name: "Bitget", src: "/images/logos/bitget.png", url: "https://www.bitget.com" },
        { name: "KuCoin", src: "/images/logos/kucoin.png", url: "https://www.kucoin.com" },
        { name: "Exness", src: "/images/logos/exness.png", url: "https://www.exness.com" },
        { name: "MEXC", src: "/images/logos/mexc.png", url: "https://www.mexc.com" },
        { name: "Vodafone Cash", src: "/images/logos/vodafone-cash.png" },
      ],
      services: [
        {
          name: "Payoneer",
          price: "$30",
          category: "حسابات بنكية",
          icon: "💳",
          iconImage: "/images/logos/payoneer.png",
          popular: true,
          active: true,
          sort: 1,
          description: "نوع الخدمة: حساب بنكي دولي. الهدف: استلام المدفوعات العالمية وإدارتها للتجار والمستقلين.",
        },
        {
          name: "Wise",
          price: "$30",
          category: "حسابات بنكية",
          icon: "🏦",
          iconImage: "/images/logos/wise.png",
          popular: true,
          active: true,
          sort: 2,
          description: "نوع الخدمة: حساب متعدد العملات. الهدف: تحويلات دولية برسوم منخفضة ورقم حساب محلي بعدة دول.",
        },
        {
          name: "Skrill",
          price: "$20",
          category: "محافظ إلكترونية",
          icon: "💰",
          iconImage: "/images/logos/skrill.png",
          active: true,
          sort: 3,
          description: "نوع الخدمة: محفظة إلكترونية. الهدف: مدفوعات وتحويلات رقمية سريعة مع دعم واسع للتجار.",
        },
        {
          name: "Neteller",
          price: "$20",
          category: "محافظ إلكترونية",
          icon: "💸",
          iconImage: "/images/logos/neteller.png",
          active: true,
          sort: 4,
          description: "نوع الخدمة: محفظة إلكترونية. الهدف: مدفوعات عالمية فورية وسحب ميسر للتداول والخدمات.",
        },
        {
          name: "PayPal",
          price: "$15",
          category: "محافظ إلكترونية",
          icon: "💙",
          iconImage: "/images/logos/paypal.png",
          popular: true,
          active: true,
          sort: 5,
          description: "نوع الخدمة: محفظة إلكترونية. الهدف: الدفع الآمن عبر الإنترنت والربط مع المتاجر بسهولة.",
        },
      ],
      payments: [
        { label: "فودافون كاش", value: "01062453344", icon: "📱", color: "red" },
        { label: "USDT TRC20", value: "TFUt8GRpk2R8Wv3FvoCiSUghRBQo4HrmQK", icon: "₿", color: "green" },
      ],
      features: [
        { title: "خدمة سريعة", desc: "تسليم خلال 24-48 ساعة", icon: "clock" },
        { title: "أمان مضمون", desc: "حماية كاملة لبياناتك", icon: "shield" },
        { title: "دعم مستمر", desc: "فريق دعم على مدار الساعة", icon: "users" },
        { title: "أسعار تنافسية", desc: "أفضل الأسعار في السوق", icon: "award" },
      ],
      testimonials: [
        { name: "أحمد", role: "رائد أعمال", quote: "خدمة ممتازة وسرعة في التنفيذ. أنصح بها بشدة." },
        { name: "سارة", role: "مسوّقة رقمية", quote: "سهولة في التواصل والدعم دائمًا موجود." },
        { name: "خالد", role: "مستقل", quote: "أفضل تجربة في إنشاء الحسابات والدفع الآمن." },
      ],
      cta: {
        title: "جاهز لتبدأ الآن؟",
        subtitle: "ابدأ رحلتك المالية بثقة وسرعة",
        primaryText: "ابدأ الآن",
        secondaryText: "تواصل معنا",
      },
      faq: [
        { question: "كم تستغرق عملية إنشاء الحساب؟", answer: "عادة من 24-48 ساعة حسب نوع الحساب والمتطلبات." },
        { question: "هل الخدمة آمنة ومضمونة؟", answer: "نعم، نتبع أعلى معايير الأمان ونحافظ على خصوصيتك." },
      ],
      contact: {
        title: "ابدأ معنا اليوم",
        subtitle: "فريق الدعم متاح 24/7 للإجابة على استفساراتك",
        whatsapp: "تواصل عبر واتساب",
        features: ["رد فوري", "استشارة مجانية", "ضمان الخدمة"],
      },
    },
    en: {
      site: {
        name: "kyctrust",
        description: "Modern platform for secure e-banking accounts and digital payments",
        phone: "+20-106-245-3344",
        tagline: "Your new financial identity",
        logoSrc: "/generic-app-logo.png",
      },
      hero: {
        title: "kyctrust",
        subtitle: "Complete Digital Financial Services Platform",
        description: "Get the best banking accounts and digital wallets with security and speed",
        cta: "Start Now",
        secondary: "Browse Services",
        stats: [
          { number: "1000+", label: "Happy Clients" },
          { number: "24/7", label: "Support" },
          { number: "99.9%", label: "Success Rate" },
          { number: "15+", label: "Services" },
        ],
      },
      logos: [
        { name: "Payoneer", src: "/images/logos/payoneer.png", url: "https://www.payoneer.com" },
        { name: "Wise", src: "/images/logos/wise.png", url: "https://wise.com" },
        { name: "Skrill", src: "/images/logos/skrill.png", url: "https://www.skrill.com" },
        { name: "Neteller", src: "/images/logos/neteller.png", url: "https://www.neteller.com" },
        { name: "PayPal", src: "/images/logos/paypal.png", url: "https://www.paypal.com" },
        { name: "OKX", src: "/images/logos/okx.png", url: "https://www.okx.com" },
        { name: "Bybit", src: "/images/logos/bybit.png", url: "https://www.bybit.com" },
        { name: "Bitget", src: "/images/logos/bitget.png", url: "https://www.bitget.com" },
        { name: "KuCoin", src: "/images/logos/kucoin.png", url: "https://www.kucoin.com" },
        { name: "Exness", src: "/images/logos/exness.png", url: "https://www.exness.com" },
        { name: "MEXC", src: "/images/logos/mexc.png", url: "https://www.mexc.com" },
        { name: "Vodafone Cash", src: "/images/logos/vodafone-cash.png" },
      ],
      services: [
        {
          name: "Payoneer",
          price: "$30",
          category: "Banking",
          icon: "💳",
          iconImage: "/images/logos/payoneer.png",
          popular: true,
          active: true,
          sort: 1,
          description:
            "Type: Global bank account. Purpose: Receive and manage international payments for merchants and freelancers.",
        },
        {
          name: "Wise",
          price: "$30",
          category: "Banking",
          icon: "🏦",
          iconImage: "/images/logos/wise.png",
          popular: true,
          active: true,
          sort: 2,
          description:
            "Type: Multi-currency account. Purpose: Low-fee international transfers with local account details in multiple countries.",
        },
        {
          name: "Skrill",
          price: "$20",
          category: "E-Wallets",
          icon: "💰",
          iconImage: "/images/logos/skrill.png",
          active: true,
          sort: 3,
          description: "Type: E-wallet. Purpose: Fast digital payments and transfers with broad merchant support.",
        },
        {
          name: "Neteller",
          price: "$20",
          category: "E-Wallets",
          icon: "💸",
          iconImage: "/images/logos/neteller.png",
          active: true,
          sort: 4,
          description:
            "Type: E-wallet. Purpose: Instant global payments and convenient cash outs for trading and services.",
        },
        {
          name: "PayPal",
          price: "$15",
          category: "E-Wallets",
          icon: "💙",
          iconImage: "/images/logos/paypal.png",
          popular: true,
          active: true,
          sort: 5,
          description: "Type: E-wallet. Purpose: Secure online checkout and easy store integrations.",
        },
      ],
      payments: [
        { label: "Vodafone Cash", value: "01062453344", icon: "📱", color: "red" },
        { label: "USDT TRC20", value: "TFUt8GRpk2R8Wv3FvoCiSUghRBQo4HrmQK", icon: "₿", color: "green" },
      ],
      features: [
        { title: "Fast Service", desc: "Delivery within 24-48 hours", icon: "clock" },
        { title: "Guaranteed Security", desc: "Complete protection for your data", icon: "shield" },
        { title: "Continuous Support", desc: "24/7 support team", icon: "users" },
        { title: "Competitive Prices", desc: "Best prices in the market", icon: "award" },
      ],
      testimonials: [
        { name: "Adam", role: "Founder", quote: "Super fast and reliable, highly recommended." },
        { name: "Leah", role: "Marketer", quote: "Excellent support and smooth onboarding." },
        { name: "Omar", role: "Freelancer", quote: "Best experience opening accounts and secure payments." },
      ],
      cta: {
        title: "Ready to get started?",
        subtitle: "Kick off your financial journey with confidence",
        primaryText: "Start Now",
        secondaryText: "Contact Us",
      },
      faq: [
        {
          question: "How long does account creation take?",
          answer: "Usually 24-48 hours depending on type and requirements.",
        },
        {
          question: "Is the service safe and guaranteed?",
          answer: "Yes, we follow top international security standards and keep your data private.",
        },
      ],
      contact: {
        title: "Get Started Today",
        subtitle: "Support team available 24/7 to answer your questions",
        whatsapp: "Contact via WhatsApp",
        features: ["Instant Reply", "Free Consultation", "Service Guarantee"],
      },
    },
  },
}
